WebAppMultiUserMVC/Controllers/AdminRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMultiUserMVC.Models;
using System.Data.SqlClient;
using System.Data;


namespace WebAppMultiUserMVC.Controllers
{
    public class AdminRegController : Controller
    {
        Entities dbobj = new Entities();

        // WebAppMultiUserMVC obj = new WebAppMultiUserMVC();
        // GET: AdminReg
        public ActionResult Insert_AdminPageload()
        {
            return View();
        }
        public ActionResult Insertadmin_Click(AdminInsert clsobj)
        {
            if(ModelState.IsValid)
            {
                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if(mid==0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_adminregtab(regid, clsobj.name, clsobj.address, clsobj.phone, clsobj.email);
                dbobj.sp_logininsert(regid, clsobj.username, clsobj.pass, "admin");
                clsobj.adminmsg = "success";
                return View("Insert_AdminPageload",clsobj);
            }
            else
            {
                return View("Insert_AdminPageload",clsobj);
            }
            
        }
    }
}

WebAppMultiUserMVC/Views/AdminReg/Insert_AdminPageload.cshtml
@model WebAppMultiUserMVC.Models.AdminInsert

@{
    ViewBag.Title = "Insert_AdminPageload";
}

<h2>Admin Details</h2>

<div>
    @using (Html.BeginForm("Insertadmin_Click", "AdminReg", FormMethod.Post, new { enctype = "multipart/form" }))
    {
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>

        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>

        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.pass)

        </div>
        <div>
            <label> Confirm Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            <input type="submit" value="Insert" >
            @Html.DisplayFor(m => m.adminmsg)
        </div>
    }
    </div>

WebAppMultiUserMVC/Views/AdminReg/Insertadmin_Click.cshtml
@{
    ViewBag.Title = "Insertadmin_Click";
}

<h2>Insertadmin_Click</h2>