WebAppMultiUserMVC/Models/UserInsert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAppMultiUserMVC.Models
{
    public class UserInsert
    {
        [Required(ErrorMessage = "Enter the Name")]
        public string name { get; set; }
        [Range(18, 50, ErrorMessage = "Enter the Age")]
        public int age { get; set; }        
        [Required(ErrorMessage = "Enter the Address")]
        public string address { get; set; }
       
        [Required(ErrorMessage = "Enter valid id")]
        public string email { get; set; }
        public string photo { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        [Compare("pass", ErrorMessage = "Password mismatch")]
        public string cpassword { get; set; }
        public string usermsg { get; set; }

    }
}

WebAppMultiUserMVC/Controllers/UserInsertController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMultiUserMVC.Models;
using System.Data.SqlClient;
using System.Data;


namespace WebAppMultiUserMVC.Controllers
{
    public class UserInsertController : Controller
    {
        // GET: UserInsert
        Entities dbobj = new Entities();

        // WebAppMultiUserMVC obj = new WebAppMultiUserMVC();
        // GET: AdminReg
        public ActionResult User_Pageload()
        {

            return View();
        }
        public ActionResult Insertuser_Click(UserInsert clsobj,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {//folder save
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/PHS/");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);
                    //for table save
                    var fullpath = Path.Combine("~/PHS/", fname);
                    clsobj.photo = fullpath;//set
                }
                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_userReg(regid, clsobj.name,clsobj.age, clsobj.address,clsobj.email,clsobj.photo);
                dbobj.sp_logininsert(regid, clsobj.username, clsobj.pass, "user");
                clsobj.usermsg = "success";
                return View("User_Pageload",clsobj);
            }
            else
            {
                return View("User_Pageload",clsobj);
            }

        }       
    }
}

WebAppMultiUserMVC/Views/UserInsert/Insertuser_Click.cshtml
@{
    ViewBag.Title = "Insertuser_Click";
}

<h2>Insertuser_Click</h2>

WebAppMultiUserMVC/Views/UserInsert/User_Pageload.cshtml
@model WebAppMultiUserMVC.Models.UserInsert

@{
    ViewBag.Title = "User_Pageload";
}

<h2>User Details</h2>

<div>
    @using (Html.BeginForm("Insertuser_Click", "UserInsert", FormMethod.Post, new { enctype = "multipart/form-data" }))
   
    {
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.name)
            @Html.ValidationMessageFor(m => m.name)
        </div>
        <div>
            <label>Age:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.age)
            @Html.ValidationMessageFor(m => m.age)
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>

        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Photo:</label>
        </div>
        <div>
            @Html.TextBox("file", "", new { type = "file" })

        </div>
        <div>
            <label>username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>

        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.pass)

        </div>
        <div>
            <label> Confirm Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            <input type="submit" value="Insert">
            @Html.DisplayFor(m => m.usermsg)
        </div>
    }
</div>